//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceUsuario {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUsuario.WebServiceUsuarioSoap")]
    public interface WebServiceUsuarioSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebLogin(string Email, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebLoginAsync(string Email, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebListar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebListar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebListar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebBuscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebBuscar(string Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebBuscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebBuscarAsync(string Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebInsertar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WebInsertar(int IdRol, string Nombre, string TipoDocumento, string NumDocumento, string Direccion, string Telefono, string Email, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebInsertar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WebInsertarAsync(int IdRol, string Nombre, string TipoDocumento, string NumDocumento, string Direccion, string Telefono, string Email, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebActualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WebActualizar(int Id, int IdRol, string Nombre, string TipoDocumento, string NumDocumento, string Direccion, string Telefono, string EmailAnt, string Email, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebActualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WebActualizarAsync(int Id, int IdRol, string Nombre, string TipoDocumento, string NumDocumento, string Direccion, string Telefono, string EmailAnt, string Email, string Clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebEliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WebEliminar(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebEliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WebEliminarAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebActivar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WebActivar(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebActivar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WebActivarAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebDesactivar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WebDesactivar(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebDesactivar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WebDesactivarAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceUsuarioSoapChannel : CapaGUI.ServiceUsuario.WebServiceUsuarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceUsuarioSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceUsuario.WebServiceUsuarioSoap>, CapaGUI.ServiceUsuario.WebServiceUsuarioSoap {
        
        public WebServiceUsuarioSoapClient() {
        }
        
        public WebServiceUsuarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceUsuarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUsuarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUsuarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet WebLogin(string Email, string Clave) {
            return base.Channel.WebLogin(Email, Clave);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebLoginAsync(string Email, string Clave) {
            return base.Channel.WebLoginAsync(Email, Clave);
        }
        
        public System.Data.DataSet WebListar() {
            return base.Channel.WebListar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebListarAsync() {
            return base.Channel.WebListarAsync();
        }
        
        public System.Data.DataSet WebBuscar(string Valor) {
            return base.Channel.WebBuscar(Valor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebBuscarAsync(string Valor) {
            return base.Channel.WebBuscarAsync(Valor);
        }
        
        public string WebInsertar(int IdRol, string Nombre, string TipoDocumento, string NumDocumento, string Direccion, string Telefono, string Email, string Clave) {
            return base.Channel.WebInsertar(IdRol, Nombre, TipoDocumento, NumDocumento, Direccion, Telefono, Email, Clave);
        }
        
        public System.Threading.Tasks.Task<string> WebInsertarAsync(int IdRol, string Nombre, string TipoDocumento, string NumDocumento, string Direccion, string Telefono, string Email, string Clave) {
            return base.Channel.WebInsertarAsync(IdRol, Nombre, TipoDocumento, NumDocumento, Direccion, Telefono, Email, Clave);
        }
        
        public string WebActualizar(int Id, int IdRol, string Nombre, string TipoDocumento, string NumDocumento, string Direccion, string Telefono, string EmailAnt, string Email, string Clave) {
            return base.Channel.WebActualizar(Id, IdRol, Nombre, TipoDocumento, NumDocumento, Direccion, Telefono, EmailAnt, Email, Clave);
        }
        
        public System.Threading.Tasks.Task<string> WebActualizarAsync(int Id, int IdRol, string Nombre, string TipoDocumento, string NumDocumento, string Direccion, string Telefono, string EmailAnt, string Email, string Clave) {
            return base.Channel.WebActualizarAsync(Id, IdRol, Nombre, TipoDocumento, NumDocumento, Direccion, Telefono, EmailAnt, Email, Clave);
        }
        
        public string WebEliminar(int Id) {
            return base.Channel.WebEliminar(Id);
        }
        
        public System.Threading.Tasks.Task<string> WebEliminarAsync(int Id) {
            return base.Channel.WebEliminarAsync(Id);
        }
        
        public string WebActivar(int Id) {
            return base.Channel.WebActivar(Id);
        }
        
        public System.Threading.Tasks.Task<string> WebActivarAsync(int Id) {
            return base.Channel.WebActivarAsync(Id);
        }
        
        public string WebDesactivar(int Id) {
            return base.Channel.WebDesactivar(Id);
        }
        
        public System.Threading.Tasks.Task<string> WebDesactivarAsync(int Id) {
            return base.Channel.WebDesactivarAsync(Id);
        }
    }
}
