//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceIngreso {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceIngreso.WebServiceIngresoSoap")]
    public interface WebServiceIngresoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebListar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebListar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebListar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebBuscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebBuscar(string Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebBuscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebBuscarAsync(string Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebConsultaFechas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebConsultaFechas(System.DateTime FechaInicio, System.DateTime FechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebConsultaFechas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebConsultaFechasAsync(System.DateTime FechaInicio, System.DateTime FechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebListarDetalle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebListarDetalle(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebListarDetalle", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebListarDetalleAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebInsertar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WebInsertar(int IdProveedor, int IdUsuario, string TipoComprobante, string SerieComprobante, string NumComprobante, decimal Impuesto, decimal Total, System.Data.DataTable Detalles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebInsertar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WebInsertarAsync(int IdProveedor, int IdUsuario, string TipoComprobante, string SerieComprobante, string NumComprobante, decimal Impuesto, decimal Total, System.Data.DataTable Detalles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebAnular", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WebAnular(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebAnular", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WebAnularAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceIngresoSoapChannel : CapaGUI.ServiceIngreso.WebServiceIngresoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceIngresoSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceIngreso.WebServiceIngresoSoap>, CapaGUI.ServiceIngreso.WebServiceIngresoSoap {
        
        public WebServiceIngresoSoapClient() {
        }
        
        public WebServiceIngresoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceIngresoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceIngresoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceIngresoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet WebListar() {
            return base.Channel.WebListar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebListarAsync() {
            return base.Channel.WebListarAsync();
        }
        
        public System.Data.DataSet WebBuscar(string Valor) {
            return base.Channel.WebBuscar(Valor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebBuscarAsync(string Valor) {
            return base.Channel.WebBuscarAsync(Valor);
        }
        
        public System.Data.DataSet WebConsultaFechas(System.DateTime FechaInicio, System.DateTime FechaFin) {
            return base.Channel.WebConsultaFechas(FechaInicio, FechaFin);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebConsultaFechasAsync(System.DateTime FechaInicio, System.DateTime FechaFin) {
            return base.Channel.WebConsultaFechasAsync(FechaInicio, FechaFin);
        }
        
        public System.Data.DataSet WebListarDetalle(int Id) {
            return base.Channel.WebListarDetalle(Id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebListarDetalleAsync(int Id) {
            return base.Channel.WebListarDetalleAsync(Id);
        }
        
        public string WebInsertar(int IdProveedor, int IdUsuario, string TipoComprobante, string SerieComprobante, string NumComprobante, decimal Impuesto, decimal Total, System.Data.DataTable Detalles) {
            return base.Channel.WebInsertar(IdProveedor, IdUsuario, TipoComprobante, SerieComprobante, NumComprobante, Impuesto, Total, Detalles);
        }
        
        public System.Threading.Tasks.Task<string> WebInsertarAsync(int IdProveedor, int IdUsuario, string TipoComprobante, string SerieComprobante, string NumComprobante, decimal Impuesto, decimal Total, System.Data.DataTable Detalles) {
            return base.Channel.WebInsertarAsync(IdProveedor, IdUsuario, TipoComprobante, SerieComprobante, NumComprobante, Impuesto, Total, Detalles);
        }
        
        public string WebAnular(int Id) {
            return base.Channel.WebAnular(Id);
        }
        
        public System.Threading.Tasks.Task<string> WebAnularAsync(int Id) {
            return base.Channel.WebAnularAsync(Id);
        }
    }
}
