//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServicePersona {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePersona.WebServicePersonaSoap")]
    public interface WebServicePersonaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebListar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebListar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebListar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebListarProveedores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebListarProveedores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebListarProveedores", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebListarProveedoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebListarClientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebListarClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebListarClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebListarClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebBuscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebBuscar(string Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebBuscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebBuscarAsync(string Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebBuscarProveedores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebBuscarProveedores(string Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebBuscarProveedores", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebBuscarProveedoresAsync(string Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebBuscarClientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebBuscarClientes(string Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebBuscarClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebBuscarClientesAsync(string Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebInsertar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WebInsertar(string TipoPersona, string Nombre, string TipoDocumento, string NumDocumento, string Direccion, string Telefono, string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebInsertar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WebInsertarAsync(string TipoPersona, string Nombre, string TipoDocumento, string NumDocumento, string Direccion, string Telefono, string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebActualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WebActualizar(int Id, string TipoPersona, string NombreAnt, string Nombre, string TipoDocumento, string NumDocumento, string Direccion, string Telefono, string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebActualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WebActualizarAsync(int Id, string TipoPersona, string NombreAnt, string Nombre, string TipoDocumento, string NumDocumento, string Direccion, string Telefono, string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebEliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WebEliminar(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebEliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WebEliminarAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicePersonaSoapChannel : CapaGUI.ServicePersona.WebServicePersonaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicePersonaSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServicePersona.WebServicePersonaSoap>, CapaGUI.ServicePersona.WebServicePersonaSoap {
        
        public WebServicePersonaSoapClient() {
        }
        
        public WebServicePersonaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicePersonaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePersonaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePersonaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet WebListar() {
            return base.Channel.WebListar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebListarAsync() {
            return base.Channel.WebListarAsync();
        }
        
        public System.Data.DataSet WebListarProveedores() {
            return base.Channel.WebListarProveedores();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebListarProveedoresAsync() {
            return base.Channel.WebListarProveedoresAsync();
        }
        
        public System.Data.DataSet WebListarClientes() {
            return base.Channel.WebListarClientes();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebListarClientesAsync() {
            return base.Channel.WebListarClientesAsync();
        }
        
        public System.Data.DataSet WebBuscar(string Valor) {
            return base.Channel.WebBuscar(Valor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebBuscarAsync(string Valor) {
            return base.Channel.WebBuscarAsync(Valor);
        }
        
        public System.Data.DataSet WebBuscarProveedores(string Valor) {
            return base.Channel.WebBuscarProveedores(Valor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebBuscarProveedoresAsync(string Valor) {
            return base.Channel.WebBuscarProveedoresAsync(Valor);
        }
        
        public System.Data.DataSet WebBuscarClientes(string Valor) {
            return base.Channel.WebBuscarClientes(Valor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebBuscarClientesAsync(string Valor) {
            return base.Channel.WebBuscarClientesAsync(Valor);
        }
        
        public string WebInsertar(string TipoPersona, string Nombre, string TipoDocumento, string NumDocumento, string Direccion, string Telefono, string Email) {
            return base.Channel.WebInsertar(TipoPersona, Nombre, TipoDocumento, NumDocumento, Direccion, Telefono, Email);
        }
        
        public System.Threading.Tasks.Task<string> WebInsertarAsync(string TipoPersona, string Nombre, string TipoDocumento, string NumDocumento, string Direccion, string Telefono, string Email) {
            return base.Channel.WebInsertarAsync(TipoPersona, Nombre, TipoDocumento, NumDocumento, Direccion, Telefono, Email);
        }
        
        public string WebActualizar(int Id, string TipoPersona, string NombreAnt, string Nombre, string TipoDocumento, string NumDocumento, string Direccion, string Telefono, string Email) {
            return base.Channel.WebActualizar(Id, TipoPersona, NombreAnt, Nombre, TipoDocumento, NumDocumento, Direccion, Telefono, Email);
        }
        
        public System.Threading.Tasks.Task<string> WebActualizarAsync(int Id, string TipoPersona, string NombreAnt, string Nombre, string TipoDocumento, string NumDocumento, string Direccion, string Telefono, string Email) {
            return base.Channel.WebActualizarAsync(Id, TipoPersona, NombreAnt, Nombre, TipoDocumento, NumDocumento, Direccion, Telefono, Email);
        }
        
        public string WebEliminar(int Id) {
            return base.Channel.WebEliminar(Id);
        }
        
        public System.Threading.Tasks.Task<string> WebEliminarAsync(int Id) {
            return base.Channel.WebEliminarAsync(Id);
        }
    }
}
