//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceProducto {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProducto.WebServiceProductoSoap")]
    public interface WebServiceProductoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebListar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebListar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebListar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebBuscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebBuscar(string Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebBuscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebBuscarAsync(string Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebBuscarVenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebBuscarVenta(string Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebBuscarVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebBuscarVentaAsync(string Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebBuscarCodigo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebBuscarCodigo(string Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebBuscarCodigo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebBuscarCodigoAsync(string Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebBuscarCodigoVenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebBuscarCodigoVenta(string Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebBuscarCodigoVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebBuscarCodigoVentaAsync(string Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebInsertar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WebInsertar(int IdCategoria, string Codigo, string Nombre, decimal PrecioVenta, int Stock, string Descripcion, string Imagen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebInsertar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WebInsertarAsync(int IdCategoria, string Codigo, string Nombre, decimal PrecioVenta, int Stock, string Descripcion, string Imagen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebActualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WebActualizar(int Id, int IdCategoria, string Codigo, string NombreAnt, string Nombre, decimal PrecioVenta, int Stock, string Descripcion, string Imagen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebActualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WebActualizarAsync(int Id, int IdCategoria, string Codigo, string NombreAnt, string Nombre, decimal PrecioVenta, int Stock, string Descripcion, string Imagen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebEliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WebEliminar(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebEliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WebEliminarAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebActivar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WebActivar(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebActivar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WebActivarAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebDesactivar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WebDesactivar(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebDesactivar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WebDesactivarAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceProductoSoapChannel : CapaGUI.ServiceProducto.WebServiceProductoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceProductoSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceProducto.WebServiceProductoSoap>, CapaGUI.ServiceProducto.WebServiceProductoSoap {
        
        public WebServiceProductoSoapClient() {
        }
        
        public WebServiceProductoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceProductoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProductoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProductoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet WebListar() {
            return base.Channel.WebListar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebListarAsync() {
            return base.Channel.WebListarAsync();
        }
        
        public System.Data.DataSet WebBuscar(string Valor) {
            return base.Channel.WebBuscar(Valor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebBuscarAsync(string Valor) {
            return base.Channel.WebBuscarAsync(Valor);
        }
        
        public System.Data.DataSet WebBuscarVenta(string Valor) {
            return base.Channel.WebBuscarVenta(Valor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebBuscarVentaAsync(string Valor) {
            return base.Channel.WebBuscarVentaAsync(Valor);
        }
        
        public System.Data.DataSet WebBuscarCodigo(string Valor) {
            return base.Channel.WebBuscarCodigo(Valor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebBuscarCodigoAsync(string Valor) {
            return base.Channel.WebBuscarCodigoAsync(Valor);
        }
        
        public System.Data.DataSet WebBuscarCodigoVenta(string Valor) {
            return base.Channel.WebBuscarCodigoVenta(Valor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebBuscarCodigoVentaAsync(string Valor) {
            return base.Channel.WebBuscarCodigoVentaAsync(Valor);
        }
        
        public string WebInsertar(int IdCategoria, string Codigo, string Nombre, decimal PrecioVenta, int Stock, string Descripcion, string Imagen) {
            return base.Channel.WebInsertar(IdCategoria, Codigo, Nombre, PrecioVenta, Stock, Descripcion, Imagen);
        }
        
        public System.Threading.Tasks.Task<string> WebInsertarAsync(int IdCategoria, string Codigo, string Nombre, decimal PrecioVenta, int Stock, string Descripcion, string Imagen) {
            return base.Channel.WebInsertarAsync(IdCategoria, Codigo, Nombre, PrecioVenta, Stock, Descripcion, Imagen);
        }
        
        public string WebActualizar(int Id, int IdCategoria, string Codigo, string NombreAnt, string Nombre, decimal PrecioVenta, int Stock, string Descripcion, string Imagen) {
            return base.Channel.WebActualizar(Id, IdCategoria, Codigo, NombreAnt, Nombre, PrecioVenta, Stock, Descripcion, Imagen);
        }
        
        public System.Threading.Tasks.Task<string> WebActualizarAsync(int Id, int IdCategoria, string Codigo, string NombreAnt, string Nombre, decimal PrecioVenta, int Stock, string Descripcion, string Imagen) {
            return base.Channel.WebActualizarAsync(Id, IdCategoria, Codigo, NombreAnt, Nombre, PrecioVenta, Stock, Descripcion, Imagen);
        }
        
        public string WebEliminar(int Id) {
            return base.Channel.WebEliminar(Id);
        }
        
        public System.Threading.Tasks.Task<string> WebEliminarAsync(int Id) {
            return base.Channel.WebEliminarAsync(Id);
        }
        
        public string WebActivar(int Id) {
            return base.Channel.WebActivar(Id);
        }
        
        public System.Threading.Tasks.Task<string> WebActivarAsync(int Id) {
            return base.Channel.WebActivarAsync(Id);
        }
        
        public string WebDesactivar(int Id) {
            return base.Channel.WebDesactivar(Id);
        }
        
        public System.Threading.Tasks.Task<string> WebDesactivarAsync(int Id) {
            return base.Channel.WebDesactivarAsync(Id);
        }
    }
}
