//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaGUI.ServiceCategoria {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCategoria.WebServiceCategoriaSoap")]
    public interface WebServiceCategoriaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebListar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebListar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebListar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebBuscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebBuscar(string Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebBuscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebBuscarAsync(string Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebSeleccionar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WebSeleccionar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebSeleccionar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WebSeleccionarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebInsertar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WebInsertar(string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebInsertar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WebInsertarAsync(string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebActualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WebActualizar(int Id, string NombreAnt, string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebActualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WebActualizarAsync(int Id, string NombreAnt, string Nombre, string Descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebEliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WebEliminar(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebEliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WebEliminarAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebActivar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WebActivar(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebActivar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WebActivarAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebDesactivar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string WebDesactivar(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WebDesactivar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> WebDesactivarAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceCategoriaSoapChannel : CapaGUI.ServiceCategoria.WebServiceCategoriaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceCategoriaSoapClient : System.ServiceModel.ClientBase<CapaGUI.ServiceCategoria.WebServiceCategoriaSoap>, CapaGUI.ServiceCategoria.WebServiceCategoriaSoap {
        
        public WebServiceCategoriaSoapClient() {
        }
        
        public WebServiceCategoriaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceCategoriaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCategoriaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceCategoriaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet WebListar() {
            return base.Channel.WebListar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebListarAsync() {
            return base.Channel.WebListarAsync();
        }
        
        public System.Data.DataSet WebBuscar(string Valor) {
            return base.Channel.WebBuscar(Valor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebBuscarAsync(string Valor) {
            return base.Channel.WebBuscarAsync(Valor);
        }
        
        public System.Data.DataSet WebSeleccionar() {
            return base.Channel.WebSeleccionar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WebSeleccionarAsync() {
            return base.Channel.WebSeleccionarAsync();
        }
        
        public string WebInsertar(string Nombre, string Descripcion) {
            return base.Channel.WebInsertar(Nombre, Descripcion);
        }
        
        public System.Threading.Tasks.Task<string> WebInsertarAsync(string Nombre, string Descripcion) {
            return base.Channel.WebInsertarAsync(Nombre, Descripcion);
        }
        
        public string WebActualizar(int Id, string NombreAnt, string Nombre, string Descripcion) {
            return base.Channel.WebActualizar(Id, NombreAnt, Nombre, Descripcion);
        }
        
        public System.Threading.Tasks.Task<string> WebActualizarAsync(int Id, string NombreAnt, string Nombre, string Descripcion) {
            return base.Channel.WebActualizarAsync(Id, NombreAnt, Nombre, Descripcion);
        }
        
        public string WebEliminar(int Id) {
            return base.Channel.WebEliminar(Id);
        }
        
        public System.Threading.Tasks.Task<string> WebEliminarAsync(int Id) {
            return base.Channel.WebEliminarAsync(Id);
        }
        
        public string WebActivar(int Id) {
            return base.Channel.WebActivar(Id);
        }
        
        public System.Threading.Tasks.Task<string> WebActivarAsync(int Id) {
            return base.Channel.WebActivarAsync(Id);
        }
        
        public string WebDesactivar(int Id) {
            return base.Channel.WebDesactivar(Id);
        }
        
        public System.Threading.Tasks.Task<string> WebDesactivarAsync(int Id) {
            return base.Channel.WebDesactivarAsync(Id);
        }
    }
}
